logger:
  pretty: true
  level: info

oxygen:
  postgres:
    data_source: "host=postgres sslmode=disable dbname=oxygen user=oxygen password=oxygen pool_max_conns=32"
  server:
    port: 80
    session:
      path: /opt/oxygen/sessions/
      secret: session-secret
    cors:
      allow_origins:
        - https://app.aefbay.com
  processing:
    webhook_base_path: https://app.aefbay.com
    payment_frontend_base_path: https://app.aefbay.com
  auth:
    email:
      merchant_email: TRX887@outlook.com
      merchant_password: 9nf3UIi8OWnu@

kms:
  server:
    port: 14000
  store:
    path: /opt/oxygen/kms.db

providers:
  tatum:
    api_key: t-66b00c135d631f001d61da8c-f57a46d6da644ad685e58eb1
    test_api_key: t-66b00c135d631f001d61da8c-07bc7aef42df4e58a2951873
    tatum_hmac_secret: t-66b00c135d631f001d61da8c-f57a46d6da644ad685e58eb1
  trongrid:
    api_key: 60460075-93e3-4ec6-bd04-7509f2227050
  kms:
    host: localhost:14000
